version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=project_drf
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5430:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres -d project_drf' ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file: .env
    depends_on:
      db:
        condition: service_healthy


volumes:
  pg_data:
